//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamakolAstrology.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JamakolAstrology.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string TabBirthChart {
            get {
                return ResourceManager.GetString("TabBirthChart", resourceCulture);
            }
        }
        
        public static string TabJamakol {
            get {
                return ResourceManager.GetString("TabJamakol", resourceCulture);
            }
        }
        
        public static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        public static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        public static string TabChakras {
            get {
                return ResourceManager.GetString("TabChakras", resourceCulture);
            }
        }
        
        public static string TabBasic {
            get {
                return ResourceManager.GetString("TabBasic", resourceCulture);
            }
        }
        
        public static string TabDashas {
            get {
                return ResourceManager.GetString("TabDashas", resourceCulture);
            }
        }
        
        public static string TabAshtakavarga {
            get {
                return ResourceManager.GetString("TabAshtakavarga", resourceCulture);
            }
        }
        
        public static string TabKP {
            get {
                return ResourceManager.GetString("TabKP", resourceCulture);
            }
        }
        
        public static string TabAmshaDevata {
            get {
                return ResourceManager.GetString("TabAmshaDevata", resourceCulture);
            }
        }
        
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        public static string LabelYear {
            get {
                return ResourceManager.GetString("LabelYear", resourceCulture);
            }
        }
        
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        public static string LabelTime {
            get {
                return ResourceManager.GetString("LabelTime", resourceCulture);
            }
        }
        
        public static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        public static string LabelLat {
            get {
                return ResourceManager.GetString("LabelLat", resourceCulture);
            }
        }
        
        public static string LabelLong {
            get {
                return ResourceManager.GetString("LabelLong", resourceCulture);
            }
        }
        
        public static string LabelTZ {
            get {
                return ResourceManager.GetString("LabelTZ", resourceCulture);
            }
        }
        
        public static string BtnNow {
            get {
                return ResourceManager.GetString("BtnNow", resourceCulture);
            }
        }
        
        public static string BtnStart {
            get {
                return ResourceManager.GetString("BtnStart", resourceCulture);
            }
        }
        
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        public static string BtnCalculate {
            get {
                return ResourceManager.GetString("BtnCalculate", resourceCulture);
            }
        }
        
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        public static string BtnSavedCharts {
            get {
                return ResourceManager.GetString("BtnSavedCharts", resourceCulture);
            }
        }
        
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        public static string ChkHideDegrees {
            get {
                return ResourceManager.GetString("ChkHideDegrees", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string LabelAyanamsha {
            get {
                return ResourceManager.GetString("LabelAyanamsha", resourceCulture);
            }
        }
        
        public static string LabelSunriseMode {
            get {
                return ResourceManager.GetString("LabelSunriseMode", resourceCulture);
            }
        }
        
        public static string LabelDefCity {
            get {
                return ResourceManager.GetString("LabelDefCity", resourceCulture);
            }
        }
        
        public static string LabelDefLatitude {
            get {
                return ResourceManager.GetString("LabelDefLatitude", resourceCulture);
            }
        }
        
        public static string LabelDefLongitude {
            get {
                return ResourceManager.GetString("LabelDefLongitude", resourceCulture);
            }
        }
        
        public static string LabelDefTimezone {
            get {
                return ResourceManager.GetString("LabelDefTimezone", resourceCulture);
            }
        }
        
        public static string LabelChartFontSize {
            get {
                return ResourceManager.GetString("LabelChartFontSize", resourceCulture);
            }
        }
        
        public static string LabelJamaGrahaFont {
            get {
                return ResourceManager.GetString("LabelJamaGrahaFont", resourceCulture);
            }
        }
        
        public static string LabelTableFontSize {
            get {
                return ResourceManager.GetString("LabelTableFontSize", resourceCulture);
            }
        }
        
        public static string LabelInputFontSize {
            get {
                return ResourceManager.GetString("LabelInputFontSize", resourceCulture);
            }
        }
        
        public static string LabelDefaultTab {
            get {
                return ResourceManager.GetString("LabelDefaultTab", resourceCulture);
            }
        }
        
        public static string LabelFixedSignBoxes {
            get {
                return ResourceManager.GetString("LabelFixedSignBoxes", resourceCulture);
            }
        }
        
        public static string ChkShowInFixedPositions {
            get {
                return ResourceManager.GetString("ChkShowInFixedPositions", resourceCulture);
            }
        }
        
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        public static string SettingsInfoText {
            get {
                return ResourceManager.GetString("SettingsInfoText", resourceCulture);
            }
        }
        
        public static string SunriseCenterTrue {
            get {
                return ResourceManager.GetString("SunriseCenterTrue", resourceCulture);
            }
        }
        
        public static string SunriseTipTrue {
            get {
                return ResourceManager.GetString("SunriseTipTrue", resourceCulture);
            }
        }
        
        public static string SunriseTipApparent {
            get {
                return ResourceManager.GetString("SunriseTipApparent", resourceCulture);
            }
        }
        
        public static string SunriseCenterApparent {
            get {
                return ResourceManager.GetString("SunriseCenterApparent", resourceCulture);
            }
        }
        
        public static string TooltipSearchCity {
            get {
                return ResourceManager.GetString("TooltipSearchCity", resourceCulture);
            }
        }
        
        public static string TooltipExport {
            get {
                return ResourceManager.GetString("TooltipExport", resourceCulture);
            }
        }
        
        public static string TooltipImport {
            get {
                return ResourceManager.GetString("TooltipImport", resourceCulture);
            }
        }
        
        public static string TooltipYear {
            get {
                return ResourceManager.GetString("TooltipYear", resourceCulture);
            }
        }
        
        public static string TooltipMonth {
            get {
                return ResourceManager.GetString("TooltipMonth", resourceCulture);
            }
        }
        
        public static string TooltipDay {
            get {
                return ResourceManager.GetString("TooltipDay", resourceCulture);
            }
        }
        
        public static string PanchangaTitle {
            get {
                return ResourceManager.GetString("PanchangaTitle", resourceCulture);
            }
        }
        
        public static string LabelTithi {
            get {
                return ResourceManager.GetString("LabelTithi", resourceCulture);
            }
        }
        
        public static string LabelNakshatra {
            get {
                return ResourceManager.GetString("LabelNakshatra", resourceCulture);
            }
        }
        
        public static string LabelYoga {
            get {
                return ResourceManager.GetString("LabelYoga", resourceCulture);
            }
        }
        
        public static string LabelKarana {
            get {
                return ResourceManager.GetString("LabelKarana", resourceCulture);
            }
        }
        
        public static string LabelVara {
            get {
                return ResourceManager.GetString("LabelVara", resourceCulture);
            }
        }
        
        public static string LabelRasi {
            get {
                return ResourceManager.GetString("LabelRasi", resourceCulture);
            }
        }
        
        public static string LabelSunrise {
            get {
                return ResourceManager.GetString("LabelSunrise", resourceCulture);
            }
        }
        
        public static string LabelSunset {
            get {
                return ResourceManager.GetString("LabelSunset", resourceCulture);
            }
        }
        
        public static string LabelHora {
            get {
                return ResourceManager.GetString("LabelHora", resourceCulture);
            }
        }
        
        public static string LabelKalaHora {
            get {
                return ResourceManager.GetString("LabelKalaHora", resourceCulture);
            }
        }
        
        public static string PrasannaTitle {
            get {
                return ResourceManager.GetString("PrasannaTitle", resourceCulture);
            }
        }
        
        public static string LabelChartName {
            get {
                return ResourceManager.GetString("LabelChartName", resourceCulture);
            }
        }
        
        public static string LabelDateTimeBc {
            get {
                return ResourceManager.GetString("LabelDateTimeBc", resourceCulture);
            }
        }
        
        public static string LabelLocationLatLongTz {
            get {
                return ResourceManager.GetString("LabelLocationLatLongTz", resourceCulture);
            }
        }
        
        public static string BtnSearchPlace {
            get {
                return ResourceManager.GetString("BtnSearchPlace", resourceCulture);
            }
        }
        
        public static string LabelResult {
            get {
                return ResourceManager.GetString("LabelResult", resourceCulture);
            }
        }
        
        public static string ResultPending {
            get {
                return ResourceManager.GetString("ResultPending", resourceCulture);
            }
        }
        
        public static string ResultSuccess {
            get {
                return ResourceManager.GetString("ResultSuccess", resourceCulture);
            }
        }
        
        public static string ResultFailure {
            get {
                return ResourceManager.GetString("ResultFailure", resourceCulture);
            }
        }
        
        public static string LabelCategory {
            get {
                return ResourceManager.GetString("LabelCategory", resourceCulture);
            }
        }
        
        public static string LabelTags {
            get {
                return ResourceManager.GetString("LabelTags", resourceCulture);
            }
        }
        
        public static string BtnManage {
            get {
                return ResourceManager.GetString("BtnManage", resourceCulture);
            }
        }
        
        public static string LabelPredictionNotes {
            get {
                return ResourceManager.GetString("LabelPredictionNotes", resourceCulture);
            }
        }
        
        public static string BtnSaveUpdate {
            get {
                return ResourceManager.GetString("BtnSaveUpdate", resourceCulture);
            }
        }
        
        public static string HeaderSavedCharts {
            get {
                return ResourceManager.GetString("HeaderSavedCharts", resourceCulture);
            }
        }
        
        public static string BtnLoadChart {
            get {
                return ResourceManager.GetString("BtnLoadChart", resourceCulture);
            }
        }
        
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        public static string BtnSearchText {
            get {
                return ResourceManager.GetString("BtnSearchText", resourceCulture);
            }
        }
        
        public static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        public static string DialogSaveChart {
            get {
                return ResourceManager.GetString("DialogSaveChart", resourceCulture);
            }
        }
        
        public static string DialogSavedCharts {
            get {
                return ResourceManager.GetString("DialogSavedCharts", resourceCulture);
            }
        }
        
        public static string DialogPlaceSearch {
            get {
                return ResourceManager.GetString("DialogPlaceSearch", resourceCulture);
            }
        }
        
        public static string DialogChartDetails {
            get {
                return ResourceManager.GetString("DialogChartDetails", resourceCulture);
            }
        }
        
        public static string LabelChartNameIcon {
            get {
                return ResourceManager.GetString("LabelChartNameIcon", resourceCulture);
            }
        }
        
        public static string PlanetaryPositions {
            get {
                return ResourceManager.GetString("PlanetaryPositions", resourceCulture);
            }
        }
        
        public static string NatalChartDetails {
            get {
                return ResourceManager.GetString("NatalChartDetails", resourceCulture);
            }
        }
        
        public static string NoContentAvailable {
            get {
                return ResourceManager.GetString("NoContentAvailable", resourceCulture);
            }
        }
        
        public static string CurrentlyRunning {
            get {
                return ResourceManager.GetString("CurrentlyRunning", resourceCulture);
            }
        }
        
        public static string LabelLevels {
            get {
                return ResourceManager.GetString("LabelLevels", resourceCulture);
            }
        }
        
        public static string MenuShowBAVGrid {
            get {
                return ResourceManager.GetString("MenuShowBAVGrid", resourceCulture);
            }
        }
        
        public static string MenuShowTableView {
            get {
                return ResourceManager.GetString("MenuShowTableView", resourceCulture);
            }
        }
        
        public static string MenuShowPindas {
            get {
                return ResourceManager.GetString("MenuShowPindas", resourceCulture);
            }
        }
        
        public static string LabelCurrentVarga {
            get {
                return ResourceManager.GetString("LabelCurrentVarga", resourceCulture);
            }
        }
        
        public static string HintRightClick {
            get {
                return ResourceManager.GetString("HintRightClick", resourceCulture);
            }
        }
        
        public static string MsgChartSaved {
            get {
                return ResourceManager.GetString("MsgChartSaved", resourceCulture);
            }
        }
        
        public static string MsgSettingsSaved {
            get {
                return ResourceManager.GetString("MsgSettingsSaved", resourceCulture);
            }
        }
        
        public static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        public static string MsgExportSuccess {
            get {
                return ResourceManager.GetString("MsgExportSuccess", resourceCulture);
            }
        }
        
        public static string MsgImportSuccess {
            get {
                return ResourceManager.GetString("MsgImportSuccess", resourceCulture);
            }
        }
        
        public static string MsgNoChartsFound {
            get {
                return ResourceManager.GetString("MsgNoChartsFound", resourceCulture);
            }
        }
        
        public static string HeaderPlanet {
            get {
                return ResourceManager.GetString("HeaderPlanet", resourceCulture);
            }
        }
        
        public static string HeaderSign {
            get {
                return ResourceManager.GetString("HeaderSign", resourceCulture);
            }
        }
        
        public static string HeaderDegree {
            get {
                return ResourceManager.GetString("HeaderDegree", resourceCulture);
            }
        }
        
        public static string HeaderHouse {
            get {
                return ResourceManager.GetString("HeaderHouse", resourceCulture);
            }
        }
        
        public static string HeaderNakshatraLord {
            get {
                return ResourceManager.GetString("HeaderNakshatraLord", resourceCulture);
            }
        }
        
        public static string HeaderSpeed {
            get {
                return ResourceManager.GetString("HeaderSpeed", resourceCulture);
            }
        }
        
        public static string HeaderRetrograde {
            get {
                return ResourceManager.GetString("HeaderRetrograde", resourceCulture);
            }
        }
        
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        public static string LangTamil {
            get {
                return ResourceManager.GetString("LangTamil", resourceCulture);
            }
        }
        public static string LabelPlace {
            get {
                return ResourceManager.GetString("LabelPlace", resourceCulture);
            }
        }
        
        public static string LabelAltitude {
            get {
                return ResourceManager.GetString("LabelAltitude", resourceCulture);
            }
        }

        public static string LabelTimeZone {
            get {
                return ResourceManager.GetString("LabelTimeZone", resourceCulture);
            }
        }

        public static string LabelLunarYearMonth {
            get {
                return ResourceManager.GetString("LabelLunarYearMonth", resourceCulture);
            }
        }

        public static string LabelVedicWeekday {
            get {
                return ResourceManager.GetString("LabelVedicWeekday", resourceCulture);
            }
        }

        public static string LabelHoraLord {
            get {
                return ResourceManager.GetString("LabelHoraLord", resourceCulture);
            }
        }

        public static string LabelMahakalaHora {
            get {
                return ResourceManager.GetString("LabelMahakalaHora", resourceCulture);
            }
        }

        public static string LabelKaalaLord {
            get {
                return ResourceManager.GetString("LabelKaalaLord", resourceCulture);
            }
        }

        public static string LabelJanmaGhatis {
            get {
                return ResourceManager.GetString("LabelJanmaGhatis", resourceCulture);
            }
        }

        public static string LabelAyanamsa {
            get {
                return ResourceManager.GetString("LabelAyanamsa", resourceCulture);
            }
        }

        public static string LabelSiderealTime {
            get {
                return ResourceManager.GetString("LabelSiderealTime", resourceCulture);
            }
        }
    }
}
